### ISSUE TITLE
Show/file overwriting issue.

### ISSUE THREAD

**Issue by darkhelmet2016** [alzamer2/Crunchyroll-XML-Decoder-py3#3]
It will overwrite files if there is an uncensored version like  ://www.crunchyroll.com/senran-kagura-shinovi-master, some shows have multiple versions for cut/uncut or if it has more than one dub like Spanish or Russian. https://www.crunchyroll.com/konosuba-gods-blessing-on-this-wonderful-world. But one problem is between different publishers they use tags for Dub or sub shows and some use Dub, English Dub or other variations and the program will overwrite them if they do not specify between the different languages or tags like on Shinovi Master. Crunchy has recently started dubbing shows in multiple languages so this might be an issue when batch downloading.

**Comment by alzamer2** [comment]
i will not lie to you
i added new option to the code that let you update the code
so i'm burnt out atm
will takle this issue later

**Comment by darkhelmet2016** [comment]
Not a problem, the only shows it might effect right now are YU-NO: A girl who chants love at the bound of this world and possibly Bungo Stray Dogs and possibly Mob Psycho depending on who is handling the dub for streaming. But it might be an issue if Funimation and Crunchy are going to start sharing more shows this season and in the future again.

**Comment by alzamer2** [comment]
i updated the code
can you test it out?

**Comment by darkhelmet2016** [comment]
What was changed? Autocatch did not pick up the dub link for https://www.crunchyroll.com/yu-no-a-girl-who-chants-love-at-the-bound-of-this-world. Is there a way to have it pick like if you want only want the Spanish dub for a series that has more than one language like Mob Mob Psycho 100?
.

**Comment by alzamer2** [comment]
the code in catching link ignore any list has dub in it
what i did is making the code not overwrite finished video, so you can if the video has un cut version
i will add option later so when catching it will catch all links or only english links

**Comment by darkhelmet2016** [comment]
That could be an issue still as some use Dubbed also or English Dub unless you added in the variations.

**Comment by alzamer2** [comment]
lol sorry i meant they filter dubed links out

**Comment by darkhelmet2016** [comment]
https://www.crunchyroll.com/search?from=&q=English+Dub You can see here they use all kinds of different variations on it depending on the publisher.

**Comment by alzamer2** [comment]
ik

**Comment by darkhelmet2016** [comment]
Because like on this one Aniplex had added subbed and dubbed for each one too. https://www.crunchyroll.com/rurouni-kenshin

**Comment by darkhelmet2016** [comment]
Would it be possible to have it like how you can pick a sub language in the settings but for the different audio languages in the settings?

**Comment by alzamer2** [comment]
For now I will make it only only subed or with dub linked
I need to check many series pages to work out code that look for certain dub language

**Comment by alzamer2** [comment]
first off all sorry for the delay
second, i updated the code
can you try it out?

**Comment by alzamer2** [comment]
@darkhelmet2016 
the dub filter is in setting make sure to false it as it set as true in defult
and you may need to delete the settings,ini file

**Comment by darkhelmet2016** [comment]
Ok, but by dub filter meant more along the lines like having it where you could pick like the Spanish or German dub by itself like you can change the sub option for what subs you want as your primary and fall back.

**Comment by darkhelmet2016** [comment]
This is the source page from https://www.crunchyroll.com/mob-psycho-100 that has more than one language in it. view-source:https://www.crunchyroll.com/mob-psycho-100

**Comment by alzamer2** [comment]
lol i said this what it will look like
i will work about it

**Comment by alzamer2** [comment]
did you try 1.4?
